# config.py

#dev
MYSQL_HOST = 'XXXXXXXXXXX' 
MYSQL_USERNAME = 'XXXXXXXX'
MYSQL_PASSWORD = 'XXXXXXXX'
MYSQL_DATABASE = 'brikoleur'
MYSQL_PORT = '3307'

SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://'+MYSQL_USERNAME+':'+MYSQL_PASSWORD+'@'+MYSQL_HOST+':'+MYSQL_PORT+'/'+MYSQL_DATABASE
SERVER_HOST = '0.0.0.0'
KEY_JWT = 'mySecret'  # Prod
MAIL_SERVER = 'XXXXXXXXXXXX'
MAIL_USERNAME = 'XXXXXXX'
MAIL_PASSWORD = 'XXXXXXXXXXX'
